<h1 style="text-align: center;"><b>LG 11 and Quiz 12 Helper</b></h1>


### Compute Eigenvalues

In [4]:
import numpy as np

#make the matrix
A = np.array([[3,1,0],
              [1,3,0],
              [0,0,4]])

#find eigenvalues and eigenvectors
eigVals, eigVecs = np.linalg.eig(A)
print("eigVecs returns eigenvectors and eigVals returns eigenvalues.\n")

print("In particular, eigVecs returns eigenvectors as columns. The column eigVecs[:,i] corresponds to the eigenvalue eigVals[i]\n")

print("Eigenvalues:", eigVals)

print("\nEigenvectors:", eigVecs)

print("\nIn other words:\n")
for i in range(len(eigVals)):
    print(f"Eigenvalue {i}: {eigVals[i]}")
    print(f"Eigenvector {i}: {eigVecs[:, i]}\n")

eigVecs returns eigenvectors and eigVals returns eigenvalues.

In particular, eigVecs returns eigenvectors as columns. The column eigVecs[:,i] corresponds to the eigenvalue eigVals[i]

Eigenvalues: [4. 2. 4.]

Eigenvectors: [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]

In other words:

Eigenvalue 0: 4.0
Eigenvector 0: [0.70710678 0.70710678 0.        ]

Eigenvalue 1: 2.0
Eigenvector 1: [-0.70710678  0.70710678  0.        ]

Eigenvalue 2: 4.0
Eigenvector 2: [0. 0. 1.]



### Verify Diagonalization

In [5]:
import numpy as np
#make the matrix P
P = np.array([[0.70710678,-0.70710678 ,0],
              [0.70710678,0.70710678,0],
             [0,0,1]])
#make the matrix D
D = np.array([[4 ,0,0],
              [0,2,0],
             [0,0,4]])
#find P inverse
print("Inverse of P:")
P_inv = np.linalg.inv(P)
print(P_inv)
#verify B1 = PDP^-1
step1_mat = np.dot(D,P_inv) 
step2_mat = np.dot(P,step1_mat)
print("PDP^-1 =")
print(step2_mat)

Inverse of P:
[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
PDP^-1 =
[[3. 1. 0.]
 [1. 3. 0.]
 [0. 0. 4.]]
