<h1 style="text-align: center;"><b>Quiz LGs 9 and 10 Helper Notebook</b></h1>



In [1]:
import numpy as np
# ============================================================
# Determinants
# ============================================================

print("=== DETERMINANTS ===\n")

A = np.array([[2, 1],
              [5, 3]], dtype=float)

B = np.array([[1, 2],
              [2, 4]], dtype=float)   # singular matrix

C = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]], dtype=float)

print("Matrix A:\n", A)
print("det(A) =", np.linalg.det(A))
print()

print("Matrix B:\n", B)
print("det(B) =", np.linalg.det(B))
print("Notice det(B) is 0 → This matrix is singular (not invertible)\n")

print("Matrix C:\n", C)
print("det(C) =", np.linalg.det(C))
print()

=== PART 1: DETERMINANTS ===

Matrix A:
 [[2. 1.]
 [5. 3.]]
det(A) = 1.0000000000000002

Matrix B:
 [[1. 2.]
 [2. 4.]]
det(B) = 0.0
Notice det(B) is 0 → This matrix is singular (not invertible)

Matrix C:
 [[1. 2. 3.]
 [0. 1. 4.]
 [5. 6. 0.]]
det(C) = 0.9999999999999987



In [2]:
# ============================================================
# Inverses
# ============================================================

print("=== INVERSES ===\n")

# Invertible example
print("Inverse of A:")
A_inv = np.linalg.inv(A)
print(A_inv)
print()

=== INVERSES ===

Inverse of A:
[[ 3. -1.]
 [-5.  2.]]



In [ ]:
import numpy as np

#Matrix A = (2x3)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

#Matrix B = (3x2)
B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

#Vector v = (3x1)
v = np.array([
    [5],
    [3],
    [2]
])
mat_vec_result = np.dot(A,v)
print("A(v) should be 2x1)")
print("Shape is",mat_vec_result.shape)
print(mat_vec_result)
mat_mat_result = np.dot(A, B)
print("AB should be 2x2)")
print("Shape is", mat_mat_result.shape)
print(mat_mat_result)