## Exercise 4.1.2

In [1]:
import numpy as np

#make the matrix
A = np.array([[3,1,0],
              [1,3,0],
              [0,0,4]])

#find eigenvalues and eigenvectors
eigVals, eigVecs = np.linalg.eig(A)
print("eigVecs returns eigenvectors and eigVals returns eigenvalues.\n")

print("In particular, eigVecs returns eigenvectors as columns. The column eigVecs[:,i] corresponds to the eigenvalue eigVals[i]\n")

print("Eigenvalues:", eigVals)

print("\nEigenvectors:", eigVecs)

print("\nIn other words:\n")
for i in range(len(eigVals)):
    print(f"Eigenvalue {i}: {eigVals[i]}")
    print(f"Eigenvector {i}: {eigVecs[:, i]}\n")

eigVecs returns eigenvectors and eigVals returns eigenvalues.

In particular, eigVecs returns eigenvectors as columns. The column eigVecs[:,i] corresponds to the eigenvalue eigVals[i]

Eigenvalues: [4. 2. 4.]

Eigenvectors: [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]

In other words:

Eigenvalue 0: 4.0
Eigenvector 0: [0.70710678 0.70710678 0.        ]

Eigenvalue 1: 2.0
Eigenvector 1: [-0.70710678  0.70710678  0.        ]

Eigenvalue 2: 4.0
Eigenvector 2: [0. 0. 1.]



In [2]:
import numpy as np
#make the matrix P
P = np.array([[0.70710678,-0.70710678 ,0],
              [0.70710678,0.70710678,0],
             [0,0,1]])
#make the matrix D
D = np.array([[4 ,0,0],
              [0,2,0],
             [0,0,4]])
#find P inverse
print("Inverse of P:")
P_inv = np.linalg.inv(P)
print(P_inv)
#verify B1 = PDP^-1
step1_mat = np.dot(D,P_inv) 
step2_mat = np.dot(P,step1_mat)
print("PDP^-1 =")
print(step2_mat)

Inverse of P:
[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
PDP^-1 =
[[3. 1. 0.]
 [1. 3. 0.]
 [0. 0. 4.]]


## Exercise 4.1.3 and 4.1.4

In [3]:
import numpy as np

#make the matrix
A = np.array([[4,2],
              [1,3]])

#find eigenvalues and eigenvectors
eigVals, eigVecs = np.linalg.eig(A)
print("eigVecs returns eigenvectors and eigVals returns eigenvalues.\n")

print("In particular, eigVecs returns eigenvectors as columns. The column eigVecs[:,i] corresponds to the eigenvalue eigVals[i]\n")

print("Eigenvalues:", eigVals)

print("\nEigenvectors:", eigVecs)

print("\nIn other words:\n")
for i in range(len(eigVals)):
    print(f"Eigenvalue {i}: {eigVals[i]}")
    print(f"Eigenvector {i}: {eigVecs[:, i]}\n")

eigVecs returns eigenvectors and eigVals returns eigenvalues.

In particular, eigVecs returns eigenvectors as columns. The column eigVecs[:,i] corresponds to the eigenvalue eigVals[i]

Eigenvalues: [5. 2.]

Eigenvectors: [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]

In other words:

Eigenvalue 0: 5.0
Eigenvector 0: [0.89442719 0.4472136 ]

Eigenvalue 1: 2.0
Eigenvector 1: [-0.70710678  0.70710678]



In [4]:
import numpy as np
#make the matrix P
P = np.array([[0.89442719, -0.70710678 ],
              [0.4472136 ,0.70710678]])
#make the matrix D
D = np.array([[5 ,0],
              [0,2]])
#find P inverse
print("Inverse of P:")
P_inv = np.linalg.inv(P)
print(P_inv)
#verify B1 = PDP^-1
step1_mat = np.dot(D,P_inv) 
step2_mat = np.dot(P,step1_mat)
print("PDP^-1 =")
print(step2_mat)

Inverse of P:
[[ 0.74535599  0.74535599]
 [-0.47140453  0.94280904]]
PDP^-1 =
[[3.99999999 1.99999999]
 [1.00000001 3.00000001]]


In [5]:
import numpy as np
#make the vector
v = np.array([1, 0]) 
#multiply matrix times vector
v1 = np.dot(P_inv,v)      
print("v1 = P_inv · v =", v1)

#multiply matrix times vector
v2 = np.dot(D,v1)      
print("v2 = D · v1 =", v2)

#Hmultiply matrix times vector
v3 = np.dot(P,v2)      
print("v3 = P · v2 =", v3)

v1 = P_inv · v = [ 0.74535599 -0.47140453]
v2 = D · v1 = [ 3.72677995 -0.94280905]
v3 = P · v2 = [3.99999999 1.00000001]


In [6]:
import numpy as np
magnitude = np.linalg.norm(v)
print("|v| =", magnitude)

magnitude = np.linalg.norm(v1)
print("|v1| =", magnitude)

|v| = 1.0
|v1| = 0.8819171043457269


In [7]:
import numpy as np
j =  np.array([0, 1]) 
p_inv_j = np.dot(P_inv,j)      
dot_prod = np.dot(v1,p_inv_j)
print("dot product =",dot_prod)

dot product = 0.11111110506446986


In [8]:
col1 =  np.array([0.89442719,0.4472136 ]) 
col2 =  np.array([-0.70710678, 0.70710678]) 
dot_prod = np.dot(col1,col2)
print("dot product =",dot_prod)

dot product = -0.3162277615971403


## 4.2 Activity

In [9]:
import numpy as np
# ----- How to make a MATRIX -----
A = np.array([[1,1],
              [0,1]])

print("A=", A)

A= [[1 1]
 [0 1]]


In [10]:
import numpy as np
# ----- How to make a VECTOR -----
i = np.array([1, 0]) 
j= np.array([0, 1]) 

print("i =", i)
print("j =", j)

i = [1 0]
j = [0 1]


In [11]:
import numpy as np
# ----- How to do Matrix Vector Multiplication -----
Ai = np.dot(A, i)
Aj = np.dot(A, j)

print("Ai =", Ai)
print("Aj =", Aj)

Ai = [1 0]
Aj = [1 1]


In [12]:
import numpy as np
#compute length of vecror
length = np.linalg.norm(Ai)
print("|Ai| =", length)

|Ai| = 1.0


In [13]:
import numpy as np
# ----- How to compute the DOT PRODUCT -----
dot_prod = np.dot(Ai,Aj)      
print("Ai · Aj =", dot_prod)

Ai · Aj = 1


In [14]:
import numpy as np

#make the matrix
A = np.array([[2,2],
              [1,-1]])

#find eigenvalues and eigenvectors
eigVals, eigVecs = np.linalg.eig(A)
print("eigVecs returns eigenvectors and eigVals returns eigenvalues.\n")

print("In particular, eigVecs returns eigenvectors as columns. The column eigVecs[:,i] corresponds to the eigenvalue eigVals[i]\n")

print("Eigenvalues:", eigVals)

print("\nEigenvectors:", eigVecs)

print("\nIn other words:\n")
for i in range(len(eigVals)):
    print(f"Eigenvalue {i}: {eigVals[i]}")
    print(f"Eigenvector {i}: {eigVecs[:, i]}\n")

eigVecs returns eigenvectors and eigVals returns eigenvalues.

In particular, eigVecs returns eigenvectors as columns. The column eigVecs[:,i] corresponds to the eigenvalue eigVals[i]

Eigenvalues: [ 2.56155281 -1.56155281]

Eigenvectors: [[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]

In other words:

Eigenvalue 0: 2.5615528128088303
Eigenvector 0: [0.96276969 0.27032301]

Eigenvalue 1: -1.5615528128088303
Eigenvector 1: [-0.48963374  0.87192821]



In [15]:
import numpy as np
#make the matrix P
P = np.array([[0.96276969, -0.48963374],
              [0.27032301 , 0.87192821]])
#make the matrix D
D = np.array([[2.56 ,0],
              [0,-1.56155281]])
#find P inverse
print("Inverse of P:")
P_inv = np.linalg.inv(P)
print(P_inv)

Inverse of P:
[[ 0.89720672  0.50382896]
 [-0.27816008  0.99068183]]
